-- MySQL Script generated by MySQL Workbench
-- Fri May  9 19:35:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema construcaocivil
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `construcaocivil` ;

-- -----------------------------------------------------
-- Schema construcaocivil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `construcaocivil` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `construcaocivil` ;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  `cpf_cnpj` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_cliente_UNIQUE` ON `cliente` (`id_cliente` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `etapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etapa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `etapa` (
  `id_etapa` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data_inicio` VARCHAR(45) NOT NULL,
  `data_fim_prevista` VARCHAR(45) NOT NULL,
  `fk_projeto_etapa` INT(11) NOT NULL,
  PRIMARY KEY (`id_etapa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_etapa_UNIQUE` ON `etapa` (`id_etapa` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `material` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `material` (
  `id_material` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `unidade_medida` VARCHAR(45) NOT NULL,
  `preco_unitario` DOUBLE NOT NULL,
  PRIMARY KEY (`id_material`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_material_UNIQUE` ON `material` (`id_material` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `profissional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profissional` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `profissional` (
  `id_profissional` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_profissional`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_profissional_UNIQUE` ON `profissional` (`id_profissional` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `projeto` (
  `id_projeto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `data_inicio` VARCHAR(45) NOT NULL,
  `data_fim_prevista` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `fk_cliente_projeto` INT(11) NOT NULL,
  `fk_profissional_projetol` INT(11) NOT NULL,
  PRIMARY KEY (`id_projeto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_projeto_UNIQUE` ON `projeto` (`id_projeto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uso_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uso_material` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uso_material` (
  `id_uso_material` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` DOUBLE NOT NULL,
  `fk_material_uso_material` INT(11) NOT NULL,
  `fk_etapa_uso_material` INT(11) NOT NULL,
  PRIMARY KEY (`id_uso_material`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_uso_material_UNIQUE` ON `uso_material` (`id_uso_material` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
